version: "3.4"

services:
  database:
    image: postgres:10-alpine
    environment: 
        - POSTGRES_USER=myapp
        - POSTGRES_PASSWORD=myapp
        - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    tty: true